### ISSUE TITLE
change the case list format

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/iViz#525]
use `study_id:sample_id` separated by white characters (\t, space, \n, etc).

**Comment by adamabeshouse** [comment]
@jjgao I want to clarify what exactly is allowed:

should we allow `study_id[\s]*:[\s]*sample_id`? or not have any whitespace?

and when there's only one study selected, we can just allow `sample_id`?

Because of those two cases together, it would be quite a bit easier in the code to make `study_id:sample_id` strict, no whitespace, but it's not prohibitively hard if that's desired for UX.

**Comment by jjgao** [comment]
@adamabeshouse 

> should we allow study_id[\s]*:[\s]*sample_id? or not have any whitespace?

No. Let's use white space to separate samples.

> when there's only one study selected, we can just allow sample_id?

Good idea.
