### ISSUE TITLE
Clicking "Query this study" button returns 500 error

### ISSUE THREAD

**Issue by victoria34** [cBioPortal/iViz#599]
![screen shot 2017-08-17 at 2 56 48 pm](https://user-images.githubusercontent.com/14971266/29428825-973c55f4-835c-11e7-906a-c324f5f003e1.png)
![screen shot 2017-08-17 at 2 59 20 pm](https://user-images.githubusercontent.com/14971266/29428868-b3bfafc8-835c-11e7-9729-4365ee2e7fe0.png)

**Comment by adamabeshouse** [comment]
@zhx828 the problem is in dashboard.jsp:
![image](https://user-images.githubusercontent.com/636232/29948490-2149e74a-8e7d-11e7-89aa-aac763b38668.png)

The query being sent is missing parameters the server expects to not be null, including case set id and cancer study id - all that's sent is cancer study list.

**Comment by zhx828** [comment]
I can update that tomorrow.

**Comment by zhx828** [comment]
Ah just saw you self assigned. Thanks for the info.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3066/files
